name: Metrics
on:
  # Schedule daily updates
  #schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          plugin_calendar: yes
          plugin_calendar_limit: 6
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_limit: 4
          plugin_achievements: yes
          plugin_activity: yes
          plugin_activity_filter: issue, pr, release, fork, review, ref/create
          plugin_stackoverflow: yes
          plugin_stackoverflow_user: 3535547
          plugin_stackoverflow_sections: answers-top
          plugin_stackoverflow_limit: 3
          plugin_leetcode: yes
          plugin_leetcode_user: sanyamkhurana
          plugin_leetcode_sections: solved, skills, recent
